[package]
authors = ["Ceri Storey <cez@necrofish.org.uk>"]
license = "Apache-2.0"
name = "suppositions"
version = "0.1.0"
repository = "https://github.com/cstorey/suppositions"
documentation = "https://docs.rs/suppositions"
description = "Property testing with automagic shrinking."

[dependencies]
log = "0.3.8"
rand = "0.3.16"
hex-slice = "0.1.0"
[dev-dependencies]
env_logger = "0.4.3"
